In [41]:
from pandas_datareader import data
import datetime
from bokeh.plotting import figure, show, output_file

start=datetime.datetime(2019,5,28)
end=datetime.datetime(2019,6,28)
df=data.DataReader(name="AMD",data_source="yahoo",start=start,end=end)
df

                 High        Low       Open      Close     Volume  Adj Close
Date
2019-05-28  29.670000  27.059999  27.270000  29.049999  146949600  29.049999
2019-05-29  29.320000  27.730000  29.000000  28.090000   99969600  28.090000
2019-05-30  28.559999  27.600000  28.400000  28.030001   65289100  28.030001
2019-05-31  28.360001  27.400000  27.570000  27.410000   68667800  27.410000
2019-06-03  29.620001  27.290001  28.750000  27.580000  147532200  27.580000
2019-06-04  29.590000  27.910000  28.389999  29.570000  107549500  29.570000
2019-06-05  29.990000  29.030001  29.930000  29.500000   79481500  29.500000
2019-06-06  31.980000  29.840000  29.870001  31.820000  131267800  31.820000
2019-06-07  32.599998  31.570000  31.940001  32.410000   86841100  32.410000
2019-06-10  34.299999  33.080002  33.529999  33.230000   97668800  33.230000
2019-06-11  33.490002  31.820000  33.430000  32.410000   82834900  32.410000
2019-06-12  32.570000  31.920000  32.000000  32.180000   56298700  32.180000
2019-06-13  32.500000  31.059999  32.389999  31.389999   63556000  31.389999
2019-06-14  30.959999  30.020000  30.700001  30.360001   70373000  30.360001
2019-06-17  30.450001  29.180000  30.250000  29.200001   70865700  29.200001
2019-06-18  30.969999  29.580000  29.760000  30.450001   86444500  30.450001
2019-06-19  30.790001  30.059999  30.670000  30.500000   63233900  30.500000
2019-06-20  31.360001  29.840000  31.240000  30.010000   72418200  30.010000
2019-06-21  30.350000  28.969999  29.650000  29.100000   81861300  29.100000
2019-06-24  29.400000  28.670000  29.320000  29.260000   55724800  29.260000
2019-06-25  29.719999  28.799999  29.260000  28.860001   53680900  28.860001
2019-06-26  30.480000  29.780001  29.980000  29.920000   65064200  29.920000
2019-06-27  30.959999  30.209999  30.410000  30.740000   55499800  30.740000
2019-06-28  31.100000  30.410000  31.080000  30.455000   36518848  30.455000

In [42]:
def increase_decrease(c,o):
    if c > o:
        value="Increase"
    elif c < o:
        value="Decrease"
    else:
        value="Equal"   
        
    return value

df["Status"]=[increase_decrease(c,o) for c,o in zip(df.Close,df.Open)]

In [43]:
df["Middle"]=(df.Open+df.Close)/2
df["Height"]=abs(df.Close-df.Open)
df

,High,Low,Open,Close,Volume,Adj Close,Status,Middle,Height
Date,,,,,,,,,
2019-05-28,29.670000,27.059999,27.270000,29.049999,146949600,29.049999,Increase,28.160000,1.779999
2019-05-29,29.320000,27.730000,29.000000,28.090000,99969600,28.090000,Decrease,28.545000,0.910000
2019-05-30,28.559999,27.600000,28.400000,28.030001,65289100,28.030001,Decrease,28.215000,0.369999
2019-05-31,28.360001,27.400000,27.570000,27.410000,68667800,27.410000,Decrease,27.490000,0.160000
2019-06-03,29.620001,27.290001,28.750000,27.580000,147532200,27.580000,Decrease,28.165000,1.170000
2019-06-04,29.590000,27.910000,28.389999,29.570000,107549500,29.570000,Increase,28.980000,1.180000
2019-06-05,29.990000,29.030001,29.930000,29.500000,79481500,29.500000,Decrease,29.715000,0.430000
2019-06-06,31.980000,29.840000,29.870001,31.820000,131267800,31.820000,Increase,30.845000,1.949999
2019-06-07,32.599998,31.570000,31.940001,32.410000,86841100,32.410000,Increase,32.175000,0.469999
2019-06-10,34.299999,33.080002,33.529999,33.230000,97668800,33.230000,Decrease,33.379999,0.299999
2019-06-11,33.490002,31.820000,33.430000,32.410000,82834900,32.410000,Decrease,32.920000,1.020000
2019-06-12,32.570000,31.920000,32.000000,32.180000,56298700,32.180000,Increase,32.090000,0.180000
2019-06-13,32.500000,31.059999,32.389999,31.389999,63556000,31.389999,Decrease,31.889999,1.000000
2019-06-14,30.959999,30.020000,30.700001,30.360001,70373000,30.360001,Decrease,30.530001,0.340000
2019-06-17,30.450001,29.180000,30.250000,29.200001,70865700,29.200001,Decrease,29.725000,1.049999
2019-06-18,30.969999,29.580000,29.760000,30.450001,86444500,30.450001,Increase,30.105000,0.690001
2019-06-19,30.790001,30.059999,30.670000,30.500000,63233900,30.500000,Decrease,30.585000,0.170000
2019-06-20,31.360001,29.840000,31.240000,30.010000,72418200,30.010000,Decrease,30.625000,1.230000
2019-06-21,30.350000,28.969999,29.650000,29.100000,81861300,29.100000,Decrease,29.375000,0.549999
2019-06-24,29.400000,28.670000,29.320000,29.260000,55724800,29.260000,Decrease,29.290000,0.059999
2019-06-25,29.719999,28.799999,29.260000,28.860001,53680900,28.860001,Decrease,29.060000,0.400000
2019-06-26,30.480000,29.780001,29.980000,29.920000,65064200,29.920000,Decrease,29.950000,0.059999
2019-06-27,30.959999,30.209999,30.410000,30.740000,55499800,30.740000,Increase,30.575000,0.330000
2019-06-28,31.100000,30.410000,31.080000,30.455000,36518848,30.455000,Decrease,30.767500,0.625000

In [44]:
p=figure(x_axis_type='datetime',width=1000,height=300)
p.title.text="Candlestick Chart"

hours_12=12*60*60*1000

p.rect(df.index[df.Status=="Increase"],df.Middle[df.Status=="Increase"],
       hours_12,df.Height[df.Status=="Increase"],fill_color="green",line_color="black")

p.rect(df.index[df.Status=="Decrease"],df.Middle[df.Status=="Decrease"],
       hours_12,df.Height[df.Status=="Decrease"],fill_color="red",line_color="black")

output_file="CS.html"
show(p)